language: node_js
node_js:
  - "10"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle

script:
  - git clone https://gist.github.com/7d59ba6ebe581c1ffcc981469e226c6e.git
  - rm ./test/supply_chain.test.js
  - mv ./7d59ba6ebe581c1ffcc981469e226c6e/supply_chain.test.js ./test/supply_chain.test.js
  - ganache-cli &
  - sleep 5
  - truffle test
